import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    'getting-started',
    'package-map',
    'playground',
    'architecture',
    'development',
    {
      type: 'category',
      label: 'API reference',
      link: {
        type: 'generated-index',
        title: 'API reference',
        description:
          'Autogenerated reference for the public @pedigree-fhir/core and @pedigree-fhir/react surfaces.',
      },
      items: [{ type: 'autogenerated', dirName: 'api' }],
    },
  ],
};

export default sidebars;
